### ISSUE TITLE
bestFit skips weeks

### ISSUE THREAD

**Issue by zbraniecki** [caridy/intl-relative-time-spec#1]
The current draft in 1.3.4 'GetBestMatchUnit' specifies:

> 4. If units.[[day]] is less than 26, return "day".

That in result means that 2 weeks will be displayed as "14 days".

I believe it would be useful to switch it to:

> 4. If units.[[day]] is less than 7, return "day".

**Comment by caridy** [comment]
ah, good catch. i didnt have week unit in the first pass. I am doing 10% delta as momentjs because I didnt find any explanation about the deltas, will be great if you can help with that.

**Comment by caridy** [comment]
@ericf finally settle of not using a delta, instead using the exact numeric value that describe each unit.

**Comment by zbraniecki** [comment]
This is fixed now
