### ISSUE TITLE
Add support for 2, -2?

### ISSUE THREAD

**Issue by zbraniecki** [caridy/intl-relative-time-spec#2]
Current spec in 1.3.4 'FormatRelativeTime' states:

> 19. If v is between -1 (inclusive) and 1 (inclusive), then

while some languages provide -2,2:
http://www.unicode.org/cldr/charts/28/summary/pl.html#1531

I believe it should state:
> 19. If v is between -2 (inclusive) and 2 (inclusive), then

**Comment by caridy** [comment]
yes, first check for -1 ... 1, else -2 ... 2

**Comment by rxaviers** [comment]
Related comment: https://github.com/caridy/intl-relative-time-spec/pull/5/files#r65721645

**Comment by zbraniecki** [comment]
This is fixed now
